### ISSUE TITLE
Use crate random choice for updating fitness

### ISSUE THREAD

**Issue by StefanoD** [martinus/differential-evolution-rs#1]
You may want to consider [Rust Random Choice](https://github.com/StefanoD/Rust_Random_Choice) for updating your samples. It can handle directly float values and it is simpler to use than the rand crate.

But the crate scores the costs diffenrently: The higher, the better. So you have to do this:

``` rust
let fitness_high = MAX_VALUE - fitness_low;
```

**Comment by martinus** [comment]
Hi Stefano, I don't think your crate is appropriate here, because differential evolution does not need a fitness proportional selection.

**Comment by StefanoD** [comment]
Ok, I see. :)
